#!/bin/bash
iso_path=""
flash_mount_point="" # e.g: /dev/sdb1  use lsblk to know for sure!

# Get the options
while getopts :f:o: option; do
   case $option in
      f) # path to iso file 
        iso_path=$OPTARG;;
      o) # flash mount point
         flash_mount_point=$OPTARG;;
     \?) # Invalid option
         echo "Error: Invalid option"
         exit;;
   esac
done
[ -z "$iso_path" ] && echo " error iso path empty." && exit 
[ -z "$flash_mount_point" ] && echo " error flash mount empty." && exit 


dd bs=4M if=$iso_path of=$flash_mount_point conv=fdatasync status=progress
