#!/bin/sh

profile=`echo "default\npower\nbalance\npeformance" | dmenu -i -p "tlp profile"`
case $profile in
  default)
    cat  /home/nidal/scripts/tlp_profiles/tlp_old.conf >> /etc/tlp.conf && sudo tlp start bat
    ;;
  power)
    cat  /home/nidal/scripts/tlp_profiles/power >> /etc/tlp.conf && sudo tlp start bat
    ;;
  balance)
    cat  /home/nidal/scripts/tlp_profiles/balance >> /etc/tlp.conf && sudo tlp start
    ;;
  peformance)
    cat /home/nidal/scripts/tlp_profiles/performance >> /etc/tlp.conf && sudo tlp start ac
    ;;
esac
